### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by bropines** [sberbank-ai/ru-dalle#18]
При попытке запуститься говорит о нехватке памяти видеокарты RTX 3050ti. 
When trying to start, it indicates a lack of memory of the RTX 3050ti video card.

`◼️ Malevich is 1.3 billion params model from the family GPT3-like, that uses Russian language and text+image multi-modality.
x4 --> ready
tokenizer --> ready
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.
vae --> ready
ruclip --> ready
Traceback (most recent call last):
  File ".\Text Document.py", line 12, in <module>
    ruclip = ruclip.to(device)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 899, in to
    return self._apply(convert)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 593, in _apply
    param_applied = fn(param)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 4.00 GiB total capacity; 2.86 GiB already allocated; 0 bytes free; 2.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by Sidiusz** [comment]
Try to comment 8 line (like "# realesrgan = get_realesrgan('x4', device=device)")

**Comment by IvanLazarevsky** [comment]
Same thing with RTX 3090 and "**generation by ruDALLE**" example from README. It worked without issues on 0.0.1-rc2, but out of memory on 0.0.1-rc4 (though speedup is more than 4x). Commenting out **realesrgan** helped, but it looks tight.

**Comment by bropines** [comment]
Не помогло.
No result
`◼️ Malevich is 1.3 billion params model from the family GPT3-like, that uses Russian language and text+image multi-modality.
tokenizer --> ready
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.
vae --> ready
ruclip --> ready
Traceback (most recent call last):
  File ".\Text Document.py", line 12, in <module>
    ruclip = ruclip.to(device)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 899, in to
    return self._apply(convert)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 570, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 593, in _apply
    param_applied = fn(param)
  File "C:\Users\bropi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\nn\modules\module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 4.00 GiB total capacity; 2.87 GiB already allocated; 0 bytes free; 2.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by lazarevskiVsg** [comment]
> Не помогло. No result `◼️ 
4 гб это мало, если в модели 1.3 млрд параметров, даже если везде использовать fp16 её вес уже будет 2.6 гб. Дальше немаленький вес данных при прогоне, плюс ещё discrete vae.

**Comment by bropines** [comment]
> > Не помогло. No result `◼️
> 
> 4 гб это по идее мало, если в модели 1.3 млрд параметров, даже если везде использовать fp16 её вес уже будет 2.6 гб. Дальше немаленький вес данных при прогоне, плюс ещё discrete vae.

Это то я понял, но мой друг с 1650 на 4гб смог запустить алгоритм. После этого я и задался вопросом

**Comment by piratetm** [comment]
└─$ python3 run_script.py                                                                                                 1 ⨯
◼️ Malevich is 1.3 billion params model from the family GPT3-like, that uses Russian language and text+image multi-modality.
x4 --> ready
tokenizer --> ready
Working with z of shape (1, 256, 32, 32) = 262144 dimensions.
vae --> ready
ruclip --> ready
  0%|                                                                                                | 0/1024 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/piratetm/ru-dalle/run_script.py", line 29, in <module>
    _pil_images, _scores = generate_images(text, tokenizer, dalle, vae, top_k=top_k, images_num=images_num, top_p=top_p)
  File "/home/piratetm/ru-dalle/rudalle/pipelines.py", line 46, in generate_images
    logits, has_cache = dalle(out, attention_mask,
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/piratetm/ru-dalle/rudalle/dalle/fp16.py", line 51, in forward
    return fp16_to_fp32(self.module(*(fp32_to_fp16(inputs)), **kwargs))
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/piratetm/ru-dalle/rudalle/dalle/model.py", line 150, in forward
    transformer_output, present_has_cache = self.transformer(
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/piratetm/ru-dalle/rudalle/dalle/transformer.py", line 76, in forward
    hidden_states, present_has_cache = layer(hidden_states, mask, has_cache=has_cache, use_cache=use_cache)
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/piratetm/ru-dalle/rudalle/dalle/transformer.py", line 162, in forward
    mlp_output, mlp_has_cache = self.mlp(
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/piratetm/ru-dalle/rudalle/dalle/transformer.py", line 353, in forward
    x = self.dense_h_to_4h(hidden_states)
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/piratetm/.local/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`



└─$ nvidia-smi
Thu Nov  4 17:01:01 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 470.74       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   44C    P8    24W / 125W |    671MiB /  5936MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1052      G   /usr/lib/xorg/Xorg                271MiB |
|    0   N/A  N/A      1330      G   /usr/bin/kwin_x11                 194MiB |
|    0   N/A  N/A      1381      G   /usr/bin/plasmashell               44MiB |
|    0   N/A  N/A      1681      G   ...AAAAAAAAA= --shared-files      129MiB |
|    0   N/A  N/A      3057      G   ...gnu/libexec/kf5/kioslave5        1MiB |
|    0   N/A  N/A      3107      G   ...AAAAAAAAA= --shared-files       23MiB |
+-----------------------------------------------------------------------------+

**Comment by Elektron2016** [comment]
На GTX 1060 6GB тоже памяти не хватает.
`RuntimeError: CUDA out of memory. Tried to allocate 250.00 MiB (GPU 0; 6.00 GiB total capacity; 4.62 GiB already allocated; 229.45 MiB free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by HetagKoroev** [comment]
GTX 1660 SUPER 6BG - same issue.

**Comment by blue-fish** [comment]
In order to run the example in README.md with only 6 GB, some modifications are necessary.
https://github.com/blue-fish/ru-dalle/commit/5e065a0d40521bda5e9e0cbd1d474f503fa89143#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

To run the model "Malevich (XL)" requires a GPU with at least 6 GB VRAM. Maybe a note can be added to README.

**Comment by AlexWortega** [comment]
Please check cuda version, cuda 11.4  use less memory, also check torch and cuda toolkit version

**Comment by Elektron2016** [comment]
После обновления CUDA ошибка появляется не на 63% а на 64%. 
Изменение строчки `realesrgan = get_realesrgan('x4', device=device)`
на `realesrgan = get_realesrgan('x4', device='cpu')` дает другую ошибку
`Traceback (most recent call last):
  File "ru-dalle.py", line 29, in <module>
    _pil_images, _scores = generate_images(text, tokenizer, dalle, vae, top_k=to
p_k, images_num=images_num, top_p=top_p)
  File "D:\Python\lib\site-packages\rudalle\pipelines.py", line 60, in gen
erate_images
    images = vae.decode(codebooks)
  File "D:\Python\lib\site-packages\rudalle\vae\model.py", line 38, in dec
ode
    img = self.model.decode(z)
  File "D:\Python\lib\site-packages\rudalle\vae\model.py", line 98, in dec
ode
    quant = self.post_quant_conv(quant)
  File "D:\Python\lib\site-packages\torch\nn\modules\module.py", line 1102
, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python\lib\site-packages\torch\nn\modules\conv.py", line 446, i
n forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Python\lib\site-packages\torch\nn\modules\conv.py", line 442, i
n _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR`
Получилось выполнить только такой код:
`from rudalle.pipelines import generate_images, show, super_resolution, cherry_pick_by_clip
from rudalle import get_rudalle_model, get_tokenizer, get_vae, get_realesrgan, get_ruclip
from rudalle.utils import seed_everything

# prepare models
device = 'cuda'
dalle = get_rudalle_model('Malevich', pretrained=True, fp16=True, device=device)
realesrgan = get_realesrgan('x4', device=device)
tokenizer = get_tokenizer()
vae = get_vae().to(device)
ruclip, ruclip_processor = get_ruclip('ruclip-vit-base-patch32-v5')
ruclip = ruclip.to(device)

text = 'изображение радуги на фоне ночного города'

seed_everything(42)
pil_images = []
scores = []
for top_k, top_p, images_num in [
    (2048, 0.995, 1),
    (1536, 0.99, 1),
    (1024, 0.99, 1),
    (1024, 0.98, 1),
    (512, 0.97, 1),
    (384, 0.96, 1),
    (256, 0.95, 1),
    (128, 0.95, 1),
]:
    _pil_images, _scores = generate_images(text, tokenizer, dalle, vae, top_k=top_k, images_num=images_num, top_p=top_p)
    pil_images += _pil_images
    scores += _scores

show(pil_images, 6)`

**Comment by shonenkov** [comment]
added examples with usage ruDALL-E Malevich (XL) with GPU 3.5Gb vRAM https://github.com/sberbank-ai/ru-dalle/pull/51

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1AoolDYePUpPkRCKIu0cP9zV7lX5QGD3Z?usp=sharing) 

or [Jupyter version](https://github.com/sberbank-ai/ru-dalle/blob/master/jupyters/Malevich-3.5GB-vRAM-usage.ipynb):

**Comment by blue-fish** [comment]
Thanks @shonenkov !

I can get the VRAM usage down to 4.8 GB with Malevich (XL), but no further. This is using `ALLOWED_MEMORY = 3.5` and `DALLE_BS = 1`. I do not understand it, but `generate_codebooks()` does not follow `torch.cuda.set_per_process_memory_fraction`. It will use more GPU memory if it is available.

For testing I opened a second Python and sent a large tensor to GPU to occupy memory. If I did not leave at least 4.8 GB available, it would run out of memory during the `generate_codebooks()` step.

**Comment by bropines** [comment]
> добавлены примеры использования ruDALL-E Malevich (XL) с графическим процессором 3,5 Гб vRAM #51
> 
> [![Открыть В Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/drive/1AoolDYePUpPkRCKIu0cP9zV7lX5QGD3Z?usp=sharing)
> 
> или [версия Jupyter](https://github.com/sberbank-ai/ru-dalle/blob/master/jupyters/Malevich-3.5GB-vRAM-usage.ipynb):
> 
> @bropines надеюсь, это поможет вам

Of course, thanks, but I'm so inexperienced in this that I didn't understand how to use it. Excuse me
Конечно спасибо, но я настолько неопытен в этом, что не понял как этим пользоваться. Простите

**Comment by bropines** [comment]
I idiot sorry)

**Comment by blue-fish** [comment]
If you can complete codebook generation step without running out of memory:
#54 makes it possible to perform `'x2'` super resolution on GPU with 6 GB.
(x4, x8 still result in out of memory error)

**Comment by AndrewTrefilov** [comment]
In this pull request #57 i tested the suggested notebook https://github.com/sberbank-ai/ru-dalle/blob/master/jupyters/Malevich-3.5GB-vRAM-usage.ipynb on my 1050TI 4 Gb, and now it works, but more slow, because i was forced to in function `generate_codebooks` change arg `use_cache` to **False**
